AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MicroservicesStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Spring Boot Microservices Starter
      CodeUri: .
      Handler: lambda.App::handleRequest
      Runtime: java11
      MemorySize: 256
