AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MicroservicesStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to consume messages from SQS
      CodeUri: .
      Handler: App::handleRequest
      Runtime: java11
      MemorySize: 256
      Role:
        Fn::GetAtt: ['MicroservicesStarterFunctionRole', 'Arn']
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
                - MicroservicesStarterQueue
                - Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures

  MicroservicesStarterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: StandardQueue

  MicroservicesStarterFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - 'sqs:ReceiveMessage'
                    - 'sqs:DeleteMessage'
                    - 'sqs:GetQueueUrl'
                    - 'sqs:GetQueueAttributes'
                  Resource:
                    Fn::GetAtt:
                      - MicroservicesStarterQueue
                      - Arn
